### ISSUE TITLE
Please help to add support for iOS11

### ISSUE THREAD

**Issue by zbzriz** [nabla-c0d3/ssl-kill-switch2#40] opened 2018-03-14 12:44 UTC
Please help to add support for iOS11, current version doesn't work under ios11. Thanks!

**Comment by iamvinny** [comment] 2018-03-27 06:11
Yeah, it would be awesome to use it on iOS 11.

**Comment by mwpcheung** [comment] 2018-04-10 13:25
@iamvinny follow me

**Comment by mwpcheung** [comment] 2018-04-10 13:26
here ssl-kill for iOS11 JB   https://github.com/mwpcheung/ssl-kill-switch2

**Comment by lgq2015** [comment] 2018-04-11 03:00
There's a problem with this upgrade. I'm not doing it well. I have a version that I can work here. Need to contact me QQ 2011229763 or 2011229763@qq.com.

**Comment by bakzeit** [comment] 2018-04-12 20:59
@mwpcheung sorry .. just asking do u have a build for ios 11 support or do i need to compile it? ( im not familiar from compiling sources )
thnx

**Comment by nabla-c0d3** [comment] 2018-04-13 03:37
@bakzeit I added a compiled version at https://github.com/nabla-c0d3/ssl-kill-switch2/releases but I do not have an iOS 11 device to test it. Can you test it and let me know if it works? Thanks!

**Comment by nerozhao** [comment] 2018-04-13 07:24
Still not working for iOS11

**Comment by bakzeit** [comment] 2018-04-13 08:17
@nabla-c0d3 yes it works ..
but people need to install then reboot and jailbreak again to make it work ..
if youn dont reboot it wont work from first time install
thnx for the great work bro ;)

**Comment by mwpcheung** [comment] 2018-04-13 08:47
install the package. kill the process u wana injecting, it works.

2018-04-13 16:17 GMT+08:00 bakzeit <notifications@github.com>:

**Comment by mwpcheung** [comment] 2018-04-13 09:32
MacOS Charles v4.2.5 works well

**Comment by FurionXin** [comment] 2018-04-13 10:57
@mwpcheung But I found that it can't work for all https packets well in App Store. Some requests are okay, but others are not.

**Comment by shmakovigor** [comment] 2018-04-13 15:03
Hello! Could someone check whether it works with the latest Instagram app? Seems it doesn't... @mwpcheung @bakzeit

**Comment by McFlurriez** [comment] 2018-04-14 08:54
@mwpcheung @bakzeit 

Can you explain how it works? 
1. iOS major/minor version
2. Electra version
3. Steps to Reproduce

**Comment by bakzeit** [comment] 2018-04-14 10:53
@McFlurriez 
iOS 11.1.1 iPhone SE  Electra 1.0.1 
Killing the Process Via SSH wont work with me .. just i restart the device and re-jailbreak works fine for me ..
and thats seems weird since restarting the process will act as restarted the device .. but seems electra injection failed on the killing the process and works fine when i restart device and re-jailbreak .. idk why im not expert in this

**Comment by McFlurriez** [comment] 2018-04-14 11:02
@bakzeit thanks for the quick reply! Which app are you testing the pinning on? Twitter? TrustKit? I would love to try to reproduce.

I spent some time building and loading kill switch myself, ran it through a debugger and stepped through the network calls. In the invalid cert case, I watched it return from boringssl without even touching the helper function hook in the PR and failing. There was one odd time that I did see it properly MITM out of 10+ requests but I wasn't able to reproduce it.

**Comment by mwpcheung** [comment] 2018-04-14 12:52
@McFlurriez Would u please give us the test case ?

**Comment by nabla-c0d3** [comment] 2018-04-14 16:09
Closing this as it was confirmed that the tweak works on iOS 11. Some apps have customized how they do SSL pinning and SSL Kill Switch won't work on them (#13 , #39).

**Closed by nabla-c0d3** 2018-04-14 16:09 UTC

**Comment by McFlurriez** [comment] 2018-04-14 17:53
It doesn't work on TrustKit's Demo, pretty sure there's nothing custom there.

**Comment by MuchiMuchiPink** [comment] 2018-04-16 08:45
Doesn't work for me on Electra 1.0.4 + iOS 11.1. Appstore doesn't load at all. DB Navigator works sometimes. Both work on an iOS10 device however. I killed the SpringBoard and even rebooted the device + rejailbreak.

**Comment by ceriumx64** [comment] 2018-04-16 08:51
@MuchiMuchiPink @McFlurriez I think I know what's going on for all of you.

On iOS 11 you can't just install your MITM root cert, you also need to explicitly trust it.
You can do this by:

`Settings -> General -> About -> Certificate Trust Settings -> Flip the switch on your cert`

**Comment by MuchiMuchiPink** [comment] 2018-04-16 08:58
@ceriumx64 thanks. The Certificate for the Mallory was already trusted, however not bettercap. But both didn't work. I'll give it another shot.

**Comment by ceriumx64** [comment] 2018-04-16 09:07
If one of them is working sounds like the kill switch is working, nice!

Unfortunately if an app implements ssl pinning themselves, they won't be using the library that the kill switch hooks into. For that, you'll be out of luck.

**Comment by MuchiMuchiPink** [comment] 2018-04-16 09:14
@ceriumx64 I'm well aware that native pinning is a different beats ;) The question is why my other mitm doesn't work on the same apps that work on bettercap. Probably something at my end. Thanks everyone helping to get this working!

**Comment by MuchiMuchiPink** [comment] 2018-05-22 14:47
@blunden I had the same issue with one of my iOS11 devices. I fixed it with moving TweakInject in /Library to a backup. Then  ln -s '/Library/MobileSubstrate/DynamicLibraries' to /Library. Renamed it to TweakInject. Respring and it worked. Hope this helps. I think that's an issue coming from a beta of Electra.

**Comment by blunden** [comment] 2018-05-24 12:08
@MuchiMuchiPink Yes, the issue was that the libraries were in the wrong directory. Curiously, a collegue had one phone where they ended up in the right place automatically but on 2 other phones we had that same issue.

It also took a few tries to get it working without running into the issue @Truewebber runs into. Unfortunately I know know what we did differently that time. Reinstalling PreferenceLoader and SSL KillSwitch2 followed by copying the files from /Library/MobileSubstrate/DynamicLibraries to /Library/TweakInject/ did the trick. Doing it with the symlink as you described made it show up but it didn't actually work.

Still, it doesn't work as well as it did in previous iOS versions. Some requests still fail while others work so there seems to be an issue with either TweakInject or SSLKillSwitch2 still.

**Comment by MuchiMuchiPink** [comment] 2018-05-29 13:33
@blunden yeah, I guess I got the symlink wrong. On a device where it worked right away, both TweakInject and DynamicLibraries, point to /usr/lib/TweakInject instead. Thanks for the feedback, gonna fix my device asap.

**Comment by asad0x01** [comment] 2018-07-03 16:05
I don't know why it's not working for you. It works perfectly on my phone
(iOS 11.1.2) . Try installing SSL KILL SWITCH 2 using this method --->
https://yalujailbreak.net/install-tweaks-ios-11-electra/ .

**Comment by yoimhere** [comment] 2019-02-02 10:04
> @bakzeit I added a compiled version at https://github.com/nabla-c0d3/ssl-kill-switch2/releases but I do not have an iOS 11 device to test it. Can you test it and let me know if it works? Thanks!

not work
