### ISSUE TITLE
Not working on iOS 11.4.1

### ISSUE THREAD

**Issue by nicolas17** [nabla-c0d3/ssl-kill-switch2#62] opened 2019-05-26 00:35 UTC
I'm on iPhone6,1 (5s), iOS 11.4.1, jailbroken with unc0ver. When intercepting the network using mitmproxy, without ssl-kill-switch, some apps work (like Safari and Cydia's home page) while others don't due to pinning (like the App Store and [Arlo](https://itunes.apple.com/us/app/arlo/id925911312)'s login).

After installing `com.nablac0d3.sslkillswitch2_0.13.deb` and enabling it, connections still fail in AppStore and Arlo, but also start failing in Safari and Cydia! The only thing that works is apt and some background daemon requests (such as geod; they probably haven't even loaded Substrate and need a restart).

For Arlo, some Google analytics and Facebook SDK requests succeed when ssl-kill-switch is disabled, only the main login fails. With ssl-kill-switch enabled, all requests fail. Note that Arlo seems to use TrustKit; at least I see it reporting to `https://overmind.datatheorem.com/trustkit/report`.

**Comment by nicolas17** [comment] 2019-05-26 00:43
I tried downgrading to sslkillswitch2_0.12 in case it was a regression introduced with the iOS12 support in 0.13, but it has the same problem.

**Comment by bryankeller** [comment] 2019-06-24 02:10
+1, Snapchat, for example, doesn't seem to work

**Comment by wangwanjie** [comment] 2019-06-24 05:14
+1, the same as above, iPhone SE, 11.4.1 jailbroken with unc0ver

**Comment by frankl1m** [comment] 2019-07-17 02:45
I urgently need, I have my research project stopped because of SSL pinning, I can also get an iPad from a friend with iOS 11.4.1 and jailbreak. Some of you have tried it in this version mainly for Settings.app

**Comment by nabla-c0d3** [comment] 2019-11-19 23:27
Duplicate of https://github.com/nabla-c0d3/ssl-kill-switch2/issues/69

**Closed by nabla-c0d3** 2019-11-19 23:27 UTC

**Comment by nicolas17** [comment] 2019-11-19 23:40
#69 is about a crash. I'm not getting any crashes here, it just makes requests fail.

**Comment by kasnder** [comment] 2019-11-25 10:10
I have the same configuration (iOS 11 + iPhone 5S). Yet, unlike #69, Unc0ver does not use Substitute but Cydia Substrate. Hence, I don't think it's a duplicate of #69, and any help would be appreciated!
