### ISSUE TITLE
iOS 12 support

### ISSUE THREAD

**Issue by trerter** [nabla-c0d3/ssl-kill-switch2#58] opened 2019-03-29 20:17 UTC
Please, rebuild for ios 12
thanks

**Comment by qunuan** [comment] 2019-04-01 03:14
```
Please, rebuild for ios 12
thanks
```

**Comment by lbbniu** [comment] 2019-04-01 07:39
Please, rebuild for ios 12
thanks

**Comment by zj1842** [comment] 2019-04-01 10:50
please, rebuild for ios 12, thanks, we need this.

**Comment by stypr** [comment] 2019-04-08 11:00
Please, rebuild for ios 12
thanks

**Comment by caoxiangyu666** [comment] 2019-04-15 07:54
Please, rebuild for ios 12
thanks

**Comment by jonluca** [comment] 2019-04-17 05:35
I've rebuilt a version for iOS 12. It is exactly the same as `HEAD` on this repo, so I'm not sure if anything has actually changed.

I've hosted it on the Cydia repo `https://jonlu.ca/repo/`.

**Comment by thierbig** [comment] 2019-04-22 00:38
Hey ! Please rebuild for ios 12 :)

**Comment by dhogberg** [comment] 2019-04-26 01:53
Pleaseee, iOS 12. Thank you!

**Comment by nabla-c0d3** [comment] 2019-04-28 17:31
Duplicate of #55

**Closed by nabla-c0d3** 2019-04-28 17:31 UTC
